In [1]:
import torch
import numpy as np
x = torch.rand(5, 3)
print(x)

tensor([[0.3045, 0.4628, 0.5721],
        [0.7525, 0.5043, 0.3177],
        [0.3070, 0.0652, 0.0185],
        [0.0537, 0.7975, 0.7683],
        [0.2390, 0.3741, 0.9744]])


In [2]:
a=torch.tensor(8)
a

tensor(8)

In [3]:
x.shape

torch.Size([5, 3])

In [4]:
x.ndim

2

In [5]:
x[:,0]

tensor([0.3045, 0.7525, 0.3070, 0.0537, 0.2390])

In [6]:
x[0]

tensor([0.3045, 0.4628, 0.5721])

In [7]:
color_img=torch.rand(3,224,224)

In [8]:
zeroes=torch.zeros(3,3)
zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [9]:
ones=torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.arange(1,11)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
? torch.arange

In [12]:
evens=torch.arange(0,11,2)

In [13]:
torch.zeros_like(evens)

tensor([0, 0, 0, 0, 0, 0])

In [14]:
tensor_type=torch.tensor([2,4,6],dtype=torch.float16,device=None,requires_grad=False)
tensor_type
#device is for google colab realy i think
#gradients? idk what that is yet
#torch.float16==torch.half

tensor([2., 4., 6.], dtype=torch.float16)

In [15]:
tensor_type.dtype

torch.float16

In [16]:
? requires_grad

Object ` requires_grad` not found.


In [17]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [18]:
tensor*10

tensor([10, 20, 30])

In [19]:
tensor*tensor

tensor([1, 4, 9])

In [20]:
torch.matmul(tensor,tensor)

tensor(14)

In [21]:
A=torch.stack([tensor,tensor],dim=0)
A

tensor([[1, 2, 3],
        [1, 2, 3]])

In [22]:
B=torch.stack([tensor,tensor],dim=1)
B

tensor([[1, 1],
        [2, 2],
        [3, 3]])

In [23]:
torch.cat([tensor,tensor])

tensor([1, 2, 3, 1, 2, 3])

In [24]:
A@B#(2,3) (3,2)=(2,2)
print(A@B,f"\n\n{(A@B).shape}")

tensor([[14, 14],
        [14, 14]]) 

torch.Size([2, 2])


In [25]:
B@A#(3,2)(2,3)=(3,3)
print(B@A,f"\n\n{(B@A).shape}")

tensor([[ 2,  4,  6],
        [ 4,  8, 12],
        [ 6, 12, 18]]) 

torch.Size([3, 3])


In [26]:
torch.max(B@A)

tensor(18)

In [27]:
torch.mean(B@A)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [28]:
torch.mean((B@A).type(torch.float32)),(B@A).type(torch.float32).mean() #NOTE: torch.mean requires float 32!!

(tensor(8.), tensor(8.))

In [29]:
(B@A).sum(),(B@A).type(torch.float32).sum()

(tensor(72), tensor(72.))

In [30]:
(B@A).argmin(),(B@A).argmax()

(tensor(0), tensor(8))

In [31]:
(A@B).argmin(),(A@B).argmax()

(tensor(0), tensor(0))

<font size="3">

* Reshaping: Reshapes an input tensor into a defined shape

* View:      Returns a view of an input tensor of a certain shape (keeping OG memory)

* Stacking:  Combines (concatenates) tensors on top (vstack) or side by side (hstack)

* Squeeze: Removes all `1` dimensions from tensor
    
* Squeeze: Add `1` dimension to tensor
    
* Permute: Return a view of tensor with dimensions permuted (swapped) in some way

In [32]:
x=torch.arange(1,11)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
print(f"{x.reshape(1,10)}\n\n{x.reshape(10,1)}\n\n")

print(f"{x.reshape(2,5)}\n\n{x.reshape(5,2)}\n\n{x.reshape(5,2,1)}\n\n{x.reshape(5,1,2)}")

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])


tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

tensor([[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]],

        [[ 7],
         [ 8]],

        [[ 9],
         [10]]])

tensor([[[ 1,  2]],

        [[ 3,  4]],

        [[ 5,  6]],

        [[ 7,  8]],

        [[ 9, 10]]])


In [34]:
print(f"{x.view(1,10)}\n\n{x.view(10,1)}\n\n")

print(f"{x.view(2,5)}\n\n{x.view(5,2)}\n\n{x.view(5,2,1)}\n\n{x.view(5,1,2)}")

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])


tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

tensor([[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]],

        [[ 7],
         [ 8]],

        [[ 9],
         [10]]])

tensor([[[ 1,  2]],

        [[ 3,  4]],

        [[ 5,  6]],

        [[ 7,  8]],

        [[ 9, 10]]])


In [35]:
print(f"{torch.stack([x,x+1,x+2],dim=0)}\n\n{torch.stack([x,x+1,x+2],dim=1)}")

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

tensor([[ 1,  2,  3],
        [ 2,  3,  4],
        [ 3,  4,  5],
        [ 4,  5,  6],
        [ 5,  6,  7],
        [ 6,  7,  8],
        [ 7,  8,  9],
        [ 8,  9, 10],
        [ 9, 10, 11],
        [10, 11, 12]])


In [36]:
x.shape

torch.Size([10])

In [37]:
x=x.reshape(1,10)
x,x.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [38]:
x=x.squeeze()
x,x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [39]:
x=x.squeeze()
x=x.unsqueeze(dim=0)
x,x.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [40]:
x=x.squeeze()
x=x.unsqueeze(dim=1)
x,x.shape

(tensor([[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10]]),
 torch.Size([10, 1]))

In [41]:
x_color=torch.rand(size=(224,224,3))
x_color_permuted=x_color.permute(2,0,1)
x_color_permuted.shape         #Important: for changing the shape

torch.Size([3, 224, 224])

<font size="3">


$$\text{PyTorch Indexing} \simeq\text{Numpy Indexing}$$

In [42]:
a=torch.arange(1,10).reshape(1,3,3)
a,a.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [43]:
a[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [44]:
a[0,0]

tensor([1, 2, 3])

In [45]:
a[0,0,0]

tensor(1)

In [46]:
a[0,2,2]

tensor(9)

In [47]:
print(f"{a[:,:,0]}\n{a[:,:,1]}\n{a[:,:,2]}")

tensor([[1, 4, 7]])
tensor([[2, 5, 8]])
tensor([[3, 6, 9]])


In [48]:
print(f"{a[:,0,0]}\n{a[:,1,1]}\n{a[:,2,2]}")

tensor([1])
tensor([5])
tensor([9])


In [49]:
a[0,0,:]

tensor([1, 2, 3])

In [50]:
a[:,:,2]

tensor([[3, 6, 9]])

<font size="3">
    
PyTorch has NumPy functionality:
    
    
* NumPy->PyTorch: `torch.from_numpy(ndarray)`
    
* PyTorch->NumPy: `torch.Tensor.numpy()`

In [51]:
array=np.arange(1,8)
array,torch.from_numpy(array)  #Note!! NumPy->PyTorch makes float64 unless .dtype specified

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [52]:
tensor=torch.ones(7)

In [53]:
tensor,tensor.numpy() #Goes back to float32... Also, New Tensor does not share memory.

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

<font size='3'>
    
To make experiments reproducible: __Use Seeds!!__

In [54]:
seed=1234

torch.manual_seed(seed)
onerand=torch.rand(3,3)

torch.manual_seed(seed)#we have to reset because... we have to
tworand=torch.rand(3,3)

onerand,tworand

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006],
         [0.0518, 0.4681, 0.6738]]),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006],
         [0.0518, 0.4681, 0.6738]]))

In [56]:
x[0].item()#<- turns (scalar) tensor into ordinary Python variable

1

In [59]:
%reset -f